/* ==========================================================================
   tu-dien.js — TỪ ĐIỂN ĐA NGÔN NGỮ (I18N)
   Tách từ index.html, không đổi logic: script dòng 1829–2097.
   Hằng toàn cục I18N: bản dịch 9 ngôn ngữ (vi, en-US, en-GB, zh, ko, ja, fr, de, es) cho mọi key data-i18n. Được dich-thuat.js dùng.
   ========================================================================== */
const I18N = {
  'nav.home.text': { vi: 'Trang chủ', 'en-US': 'Home', 'en-GB': 'Home', zh: '首页', ko: '홈', ja: 'ホーム', fr: 'Accueil', de: 'Startseite', es: 'Inicio' },
  'nav.products.text': { vi: 'Sản phẩm', 'en-US': 'Products', 'en-GB': 'Products', zh: '产品', ko: '제품', ja: '製品', fr: 'Produits', de: 'Produkte', es: 'Productos' },
  'nav.products.game.text': { vi: 'Trò chơi trên các nền tảng', 'en-US': 'Games on platforms', 'en-GB': 'Games on platforms', zh: '各平台游戏', ko: '플랫폼 게임', ja: '各プラットフォームのゲーム', fr: 'Jeux sur plateformes', de: 'Spiele auf Plattformen', es: 'Juegos en plataformas' },
  'nav.products.movie.text': { vi: 'Phim trên các nền tảng', 'en-US': 'Movies on platforms', 'en-GB': 'Movies on platforms', zh: '各平台电影', ko: '플랫폼 영화', ja: '各プラットフォームの映画', fr: 'Films sur plateformes', de: 'Filme auf Plattformen', es: 'Películas en plataformas' },
  'nav.products.digital.text': { vi: 'Sản phẩm kỹ thuật số', 'en-US': 'Digital products', 'en-GB': 'Digital products', zh: '数字产品', ko: '디지털 제품', ja: 'デジタル製品', fr: 'Produits numériques', de: 'Digitale Produkte', es: 'Productos digitales' },
  'nav.products.electronics.text': { vi: 'Điện tử & công nghiệp', 'en-US': 'Electronics & Industrial', 'en-GB': 'Electronics & Industrial', zh: '电子与工业', ko: '전자 및 산업', ja: '電子・産業', fr: 'Électronique & Industriel', de: 'Elektronik & Industrie', es: 'Electrónica e Industrial' },
  'nav.partners.text': { vi: 'Đối tác & nhà cung cấp', 'en-US': 'Partners & Suppliers', 'en-GB': 'Partners & Suppliers', zh: '合作伙伴与供应商', ko: '파트너 및 공급업체', ja: 'パートナーとサプライヤー', fr: 'Partenaires & Fournisseurs', de: 'Partner & Lieferanten', es: 'Socios y Proveedores' },
  'nav.support.text': { vi: 'Dịch vụ khách hàng', 'en-US': 'Customer Service', 'en-GB': 'Customer Service', zh: '客户服务', ko: '고객 서비스', ja: 'カスタマーサービス', fr: 'Service client', de: 'Kundenservice', es: 'Servicio al cliente' },
  'nav.offers.text': { vi: 'Ưu đãi hôm nay', 'en-US': "Today's Deals", 'en-GB': "Today's Deals", zh: '今日优惠', ko: '오늘의 특가', ja: '今日のお得情報', fr: 'Offres du jour', de: 'Heutige Angebote', es: 'Ofertas de hoy' },
  'nav.sell.text': { vi: 'Đăng ký bán hàng', 'en-US': 'Become a Seller', 'en-GB': 'Become a Seller', zh: '注册成为卖家', ko: '판매자 등록', ja: '販売者登録', fr: 'Devenir vendeur', de: 'Verkäufer werden', es: 'Convertirse en vendedor' },
  'panel.navigation': { vi: 'Điều hướng', 'en-US': 'Navigation', 'en-GB': 'Navigation', zh: '导航', ko: '내비게이션', ja: 'ナビゲーション', fr: 'Navigation', de: 'Navigation', es: 'Navegación' },
  'panel.products': { vi: 'Sản phẩm', 'en-US': 'Products', 'en-GB': 'Products', zh: '产品', ko: '제품', ja: '製品', fr: 'Produits', de: 'Produkte', es: 'Productos' },
  'panel.support': { vi: 'Hỗ trợ', 'en-US': 'Support', 'en-GB': 'Support', zh: '支持', ko: '지원', ja: 'サポート', fr: 'Support', de: 'Support', es: 'Soporte' },
  'panel.utilities': { vi: 'Tiện ích', 'en-US': 'Utilities', 'en-GB': 'Utilities', zh: '工具', ko: '유틸리티', ja: 'ユーティリティ', fr: 'Utilitaires', de: 'Dienstprogramme', es: 'Utilidades' },
  'panel.language': { vi: 'Ngôn ngữ', 'en-US': 'Language', 'en-GB': 'Language', zh: '语言', ko: '언어', ja: '言語', fr: 'Langue', de: 'Sprache', es: 'Idioma' },
  'panel.cart': { vi: 'Giỏ hàng', 'en-US': 'Cart', 'en-GB': 'Basket', zh: '购物车', ko: '장바구니', ja: 'カート', fr: 'Panier', de: 'Warenkorb', es: 'Carrito' },
  'scroll.hint': { vi: 'Cuộn để khám phá', 'en-US': 'Scroll to explore', 'en-GB': 'Scroll to explore', zh: '滚动探索', ko: '스크롤하여 탐색', ja: 'スクロールして探索', fr: 'Faites défiler', de: 'Scrollen zum Entdecken', es: 'Desplázate para explorar' },
  'intro.eyebrow': {
    vi: 'Digital Tech Resolution',
    'en-US': 'Digital Tech Resolution',
    'en-GB': 'Digital Tech Resolution',
    zh: '数字科技革命',
    ko: '디지털 테크 레볼루션',
    ja: 'デジタルテックレボリューション',
    fr: 'Révolution Tech Digitale',
    de: 'Digitale Tech-Resolution',
    es: 'Revolución Tecnológica Digital'
  },
  'intro.desc': {
    vi: 'DTR-Mart là nền tảng <span>thương mại số thế hệ mới</span>, được xây dựng để kết nối doanh nghiệp, nhà cung cấp và khách hàng trên khắp thế giới trong cùng một hệ sinh thái liền mạch. Tại đây, công nghệ phục vụ thương mại, dữ liệu nâng tầm trải nghiệm và mọi giao dịch đều đặt <span>niềm tin</span> làm nền tảng — để <span>mỗi đối tác cùng phát triển, cùng bứt phá</span> và chia sẻ giá trị bền vững trên hành trình chuyển đổi số.',
    'en-US': 'DTR-Mart is a <span>next-generation digital commerce platform</span> built to connect businesses, suppliers and customers across the globe within one seamless ecosystem. Here, technology serves commerce, data elevates every experience and every transaction is grounded in <span>trust</span> — so <span>every partner can grow and break through together</span>, sharing lasting value on the journey of digital transformation.',
    'en-GB': 'DTR-Mart is a <span>next-generation digital commerce platform</span> built to connect businesses, suppliers and customers across the globe within one seamless ecosystem. Here, technology serves commerce, data elevates every experience and every transaction is grounded in <span>trust</span> — so <span>every partner can grow and break through together</span>, sharing lasting value on the journey of digital transformation.',
    zh: 'DTR-Mart 是一个<span>新一代数字商务平台</span>，旨在将全球的企业、供应商与客户连接在同一个无缝生态之中。在这里，技术服务商业，数据提升体验，每一笔交易都以<span>信任</span>为基石——让<span>每一位伙伴共同成长、共同突破</span>，在数字化转型的旅程中共享持久价值。',
    ko: 'DTR-Mart는 기업, 공급업체, 고객을 하나의 매끄러운 생태계로 연결하는 <span>차세대 디지털 커머스 플랫폼</span>입니다. 여기서 기술은 상거래를 돕고, 데이터가 경험을 높이며, 모든 거래는 <span>신뢰</span> 위에 세워집니다 — <span>모든 파트너가 함께 성장하고 함께 도약</span>하며 디지털 전환 여정에서 지속 가능한 가치를 나눕니다.',
    ja: 'DTR-Mart は、企業・サプライヤー・顧客を一つのシームレスなエコシステムでつなぐ<span>次世代デジタルコマースプラットフォーム</span>です。テクノロジーが商取引を支え、データが体験を高め、すべての取引は<span>信頼</span>を土台に行われます。<span>すべてのパートナーが共に成長し、共に飛躍</span>できるよう、デジタルトランスフォーメーションの旅路で持続可能な価値を分かち合います。',
    fr: "DTR-Mart est une <span>plateforme de commerce numérique nouvelle génération</span> conçue pour relier entreprises, fournisseurs et clients à travers le monde au sein d’un écosystème fluide. Ici, la technologie sert le commerce, les données subliment l’expérience et chaque transaction repose sur la <span>confiance</span> — afin que <span>chaque partenaire progresse et percute ensemble</span>, en partageant une valeur durable sur le chemin de la transformation numérique.",
    de: 'DTR-Mart ist eine <span>Handelsplattform der nächsten Generation</span>, die Unternehmen, Lieferanten und Kunden weltweit in einem nahtlosen Ökosystem verbindet. Hier dient Technologie dem Handel, Daten erhöhen das Erlebnis und jede Transaktion basiert auf <span>Vertrauen</span> — damit <span>jeder Partner gemeinsam wachsen und durchstarten</span> und nachhaltige Werte auf dem Weg der digitalen Transformation teilen kann.',
    es: 'DTR-Mart es una <span>plataforma de comercio digital de nueva generación</span> diseñada para conectar empresas, proveedores y clientes de todo el mundo en un mismo ecosistema fluido. Aquí la tecnología sirve al comercio, los datos elevan la experiencia y cada transacción se cimenta en la <span>confianza</span> — para que <span>cada socio crezca y se supere junto a los demás</span>, compartiendo valor duradero en el camino de la transformación digital.'
  },
  'globe.title': {
    vi: 'Kết nối <span>thương mại toàn cầu</span>',
    'en-US': 'Connecting <span>global trade</span>',
    'en-GB': 'Connecting <span>global trade</span>',
    zh: '连接<span>全球贸易</span>',
    ko: '<span>글로벌 무역</span>을 연결합니다',
    ja: '<span>グローバル貿易</span>をつなぐ',
    fr: 'Connecter le <span>commerce mondial</span>',
    de: '<span>Globalen Handel</span> verbinden',
    es: 'Conectando el <span>comercio global</span>'
  },
  'globe.stat.countries': { vi: 'Quốc gia', 'en-US': 'Countries', 'en-GB': 'Countries', zh: '国家', ko: '국가', ja: 'カ国', fr: 'Pays', de: 'Länder', es: 'Países' },
  'globe.stat.products': { vi: 'Sản phẩm', 'en-US': 'Products', 'en-GB': 'Products', zh: '产品', ko: '제품', ja: '製品', fr: 'Produits', de: 'Produkte', es: 'Productos' },
  'globe.stat.partners': { vi: 'Đối tác', 'en-US': 'Partners', 'en-GB': 'Partners', zh: '合作伙伴', ko: '파트너', ja: 'パートナー', fr: 'Partenaires', de: 'Partner', es: 'Socios' },
  'globe.stat.support': { vi: 'Hỗ trợ', 'en-US': 'Support', 'en-GB': 'Support', zh: '支持', ko: '지원', ja: 'サポート', fr: 'Support', de: 'Support', es: 'Soporte' },
  'journey.title': {
    vi: 'Hành trình <span>DTR-Mart</span>',
    'en-US': 'The <span>DTR-Mart</span> Journey',
    'en-GB': 'The <span>DTR-Mart</span> Journey',
    zh: '<span>DTR-Mart</span> 的旅程',
    ko: '<span>DTR-Mart</span> 여정',
    ja: '<span>DTR-Mart</span> の歩み',
    fr: 'Le parcours <span>DTR-Mart</span>',
    de: 'Die <span>DTR-Mart</span>-Reise',
    es: 'El viaje de <span>DTR-Mart</span>'
  },
  'journey.subtitle': {
    vi: 'Digital Tech Resolution · Từ 2019 đến nay',
    'en-US': 'Digital Tech Resolution · Since 2019',
    'en-GB': 'Digital Tech Resolution · Since 2019',
    zh: 'Digital Tech Resolution · 自2019年起',
    ko: 'Digital Tech Resolution · 2019년부터',
    ja: 'Digital Tech Resolution · 2019年から',
    fr: 'Digital Tech Resolution · Depuis 2019',
    de: 'Digital Tech Resolution · Seit 2019',
    es: 'Digital Tech Resolution · Desde 2019'
  },
  'journey.y2019.year': { vi: '2019 — Khởi nguồn', 'en-US': '2019 — Origin', 'en-GB': '2019 — Origin', zh: '2019 — 起源', ko: '2019 — 기원', ja: '2019 — 起源', fr: '2019 — Origine', de: '2019 — Ursprung', es: '2019 — Origen' },
  'journey.y2019.title': { vi: 'Thành lập DTR Group', 'en-US': 'DTR Group founded', 'en-GB': 'DTR Group founded', zh: '成立 DTR Group', ko: 'DTR Group 설립', ja: 'DTR Group 設立', fr: 'Création de DTR Group', de: 'Gründung von DTR Group', es: 'Fundación de DTR Group' },
  'journey.y2019.desc': {
    vi: 'DTR được thành lập với tầm nhìn trở thành cầu nối thương mại số giữa Việt Nam và thị trường công nghệ toàn cầu.',
    'en-US': 'DTR was founded with the vision of becoming a digital commerce bridge between Vietnam and the global tech market.',
    'en-GB': 'DTR was founded with the vision of becoming a digital commerce bridge between Vietnam and the global tech market.',
    zh: 'DTR 的创立愿景是成为越南与全球科技市场之间的数字商务桥梁。',
    ko: 'DTR은 베트남과 글로벌 기술 시장을 잇는 디지털 상거래의 다리가 되겠다는 비전으로 설립되었습니다.',
    ja: 'DTRは、ベトナムとグローバルなテクノロジー市場をつなぐデジタル商取引の架け橋となることをビジョンに設立されました。',
    fr: "DTR a été fondée avec la vision de devenir un pont de commerce numérique entre le Vietnam et le marché technologique mondial.",
    de: 'DTR wurde mit der Vision gegründet, eine Brücke für den digitalen Handel zwischen Vietnam und dem globalen Technologiemarkt zu werden.',
    es: 'DTR fue fundada con la visión de convertirse en un puente de comercio digital entre Vietnam y el mercado tecnológico global.'
  },
  'journey.y2021.year': { vi: '2021 — Mở rộng', 'en-US': '2021 — Expansion', 'en-GB': '2021 — Expansion', zh: '2021 — 扩张', ko: '2021 — 확장', ja: '2021 — 拡大', fr: '2021 — Expansion', de: '2021 — Expansion', es: '2021 — Expansión' },
  'journey.y2021.title': { vi: 'Ra mắt nền tảng DTR-Mart', 'en-US': 'DTR-Mart platform launch', 'en-GB': 'DTR-Mart platform launch', zh: 'DTR-Mart 平台上线', ko: 'DTR-Mart 플랫폼 출시', ja: 'DTR-Mart プラットフォーム開始', fr: 'Lancement de la plateforme DTR-Mart', de: 'Start der DTR-Mart-Plattform', es: 'Lanzamiento de la plataforma DTR-Mart' },
  'journey.y2021.desc': {
    vi: 'Nền tảng DTR-Mart chính thức hoạt động, cung cấp game, phim và sản phẩm số từ hơn 20 quốc gia. Đối tác vượt mốc 1.000 nhà cung cấp.',
    'en-US': 'The DTR-Mart platform officially launched, offering games, movies and digital products from over 20 countries. Partners exceeded 1,000 suppliers.',
    'en-GB': 'The DTR-Mart platform officially launched, offering games, movies and digital products from over 20 countries. Partners exceeded 1,000 suppliers.',
    zh: 'DTR-Mart 平台正式上线，提供来自 20 多个国家的游戏、电影和数字产品。合作伙伴突破 1,000 家供应商。',
    ko: 'DTR-Mart 플랫폼이 정식 출시되어 20개 이상 국가의 게임, 영화, 디지털 제품을 제공합니다. 파트너는 1,000개 공급업체를 돌파했습니다.',
    ja: 'DTR-Mart プラットフォームが正式に稼働し、20カ国以上のゲーム、映画、デジタル製品を提供。パートナーは1,000社を超えました。',
    fr: "La plateforme DTR-Mart a officiellement lancé, proposant des jeux, films et produits numériques de plus de 20 pays. Les partenaires ont dépassé 1 000 fournisseurs.",
    de: 'Die DTR-Mart-Plattform ging offiziell an den Start und bietet Spiele, Filme und digitale Produkte aus über 20 Ländern. Partner überschritten 1.000 Lieferanten.',
    es: 'La plataforma DTR-Mart se lanzó oficialmente, ofreciendo juegos, películas y productos digitales de más de 20 países. Los socios superaron los 1.000 proveedores.'
  },
  'journey.y2023.year': { vi: '2023 — Đột phá', 'en-US': '2023 — Breakthrough', 'en-GB': '2023 — Breakthrough', zh: '2023 — 突破', ko: '2023 — 돌파구', ja: '2023 — ブレイクスルー', fr: '2023 — Percée', de: '2023 — Durchbruch', es: '2023 — Avance' },
  'journey.y2023.title': { vi: 'Mở rộng ra thị trường quốc tế', 'en-US': 'International market expansion', 'en-GB': 'International market expansion', zh: '拓展国际市场', ko: '국제 시장 확장', ja: '国際市場への進出', fr: 'Expansion sur le marché international', de: 'Expansion auf internationale Märkte', es: 'Expansión al mercado internacional' },
  'journey.y2023.desc': {
    vi: 'DTR-Mart phục vụ khách hàng tại 30+ quốc gia Đông Nam Á và châu Á - Thái Bình Dương. Ra mắt dịch vụ điện tử & công nghiệp B2B.',
    'en-US': 'DTR-Mart served customers in 30+ countries across Southeast Asia and Asia-Pacific. Launched B2B electronics & industrial services.',
    'en-GB': 'DTR-Mart served customers in 30+ countries across Southeast Asia and Asia-Pacific. Launched B2B electronics & industrial services.',
    zh: 'DTR-Mart 为东南亚和亚太地区 30 多个国家的客户提供服务。推出 B2B 电子与工业服务。',
    ko: 'DTR-Mart은 동남아시아와 아시아·태평양 30개 이상 국가의 고객에게 서비스를 제공합니다. B2B 전자 및 산업 서비스를 출시했습니다.',
    ja: 'DTR-Mart は東南アジアとアジア太平洋の30カ国以上のお客様にサービスを提供。B2B 電子・産業サービスを開始しました。',
    fr: "DTR-Mart a servi des clients dans plus de 30 pays d'Asie du Sud-Est et d'Asie-Pacifique. Lancement des services B2B électronique et industriel.",
    de: 'DTR-Mart bediente Kunden in über 30 Ländern in Südostasien und Asien-Pazifik. Start von B2B-Elektronik- und Industriedienstleistungen.',
    es: 'DTR-Mart atendió a clientes en más de 30 países del sudeste asiático y Asia-Pacífico. Lanzó servicios B2B de electrónica e industria.'
  },
  'journey.y2025.year': { vi: '2025 — Bứt phá', 'en-US': '2025 — Growth', 'en-GB': '2025 — Growth', zh: '2025 — 增长', ko: '2025 — 성장', ja: '2025 — 成長', fr: '2025 — Croissance', de: '2025 — Wachstum', es: '2025 — Crecimiento' },
  'journey.y2025.title': { vi: '50+ quốc gia, 38K+ sản phẩm', 'en-US': '50+ countries, 38K+ products', 'en-GB': '50+ countries, 38K+ products', zh: '50+ 国家，38K+ 产品', ko: '50개 이상 국가, 38K개 이상 제품', ja: '50カ国以上、38K以上の製品', fr: '50+ pays, 38K+ produits', de: '50+ Länder, 38K+ Produkte', es: '50+ países, 38K+ productos' },
  'journey.y2025.desc': {
    vi: 'Mạng lưới thương mại toàn cầu đạt 50+ quốc gia với hơn 38.000 sản phẩm số và 12.000 đối tác. Logistics thông minh kết nối real-time.',
    'en-US': 'Global trade network reached 50+ countries with over 38,000 digital products and 12,000 partners. Smart logistics connected in real-time.',
    'en-GB': 'Global trade network reached 50+ countries with over 38,000 digital products and 12,000 partners. Smart logistics connected in real-time.',
    zh: '全球贸易网络覆盖 50 多个国家，拥有超过 38,000 种数字产品和 12,000 个合作伙伴。智能物流实时互联。',
    ko: '글로벌 무역 네트워크가 50개 이상 국가, 38,000개 이상의 디지털 제품, 12,000개 파트너에 도달했습니다. 스마트 물류가 실시간으로 연결됩니다.',
    ja: 'グローバル貿易ネットワークが50カ国以上に達し、38,000以上のデジタル製品と12,000のパートナーを抱えます。スマート物流がリアルタイムで接続。',
    fr: "Le réseau commercial mondial a atteint plus de 50 pays avec plus de 38 000 produits numériques et 12 000 partenaires. Logistique intelligente connectée en temps réel.",
    de: 'Das globale Handelsnetzwerk erreichte über 50 Länder mit mehr als 38.000 digitalen Produkten und 12.000 Partnern. Smarte Logistik in Echtzeit verbunden.',
    es: 'La red comercial global alcanzó más de 50 países con más de 38.000 productos digitales y 12.000 socios. Logística inteligente conectada en tiempo real.'
  },
  'journey.y2026.year': { vi: '2026 — Tương lai', 'en-US': '2026 — Future', 'en-GB': '2026 — Future', zh: '2026 — 未来', ko: '2026 — 미래', ja: '2026 — 未来', fr: '2026 — Avenir', de: '2026 — Zukunft', es: '2026 — Futuro' },
  'journey.y2026.title': { vi: 'Kỷ nguyên AI & thương mại thông minh', 'en-US': 'The AI & smart commerce era', 'en-GB': 'The AI & smart commerce era', zh: 'AI 与智慧商业时代', ko: 'AI 및 스마트 커머스 시대', ja: 'AIとスマートコマースの時代', fr: "L'ère de l'IA et du commerce intelligent", de: 'Das Zeitalter von KI & smartem Handel', es: 'La era de la IA y el comercio inteligente' },
  'journey.y2026.desc': {
    vi: 'DTR-Mart tích hợp AI vào toàn bộ chuỗi cung ứng, cá nhân hóa trải nghiệm mua sắm và tối ưu vận hành cho đối tác toàn cầu.',
    'en-US': 'DTR-Mart integrates AI into the entire supply chain, personalizing the shopping experience and optimizing operations for global partners.',
    'en-GB': 'DTR-Mart integrates AI into the entire supply chain, personalising the shopping experience and optimising operations for global partners.',
    zh: 'DTR-Mart 将 AI 融入整个供应链，个性化购物体验，为全球合作伙伴优化运营。',
    ko: 'DTR-Mart은 AI를 전체 공급망에 통합하여 쇼핑 경험을 개인화하고 글로벌 파트너의 운영을 최적화합니다.',
    ja: 'DTR-Mart は AI をサプライチェーン全体に統合し、ショッピング体験をパーソナライズし、グローバルパートナーの運営を最適化します。',
    fr: "DTR-Mart intègre l'IA dans toute la chaîne d'approvisionnement, personnalise l'expérience d'achat et optimise les opérations pour les partenaires mondiaux.",
    de: 'DTR-Mart integriert KI in die gesamte Lieferkette, personalisiert das Einkaufserlebnis und optimiert den Betrieb für globale Partner.',
    es: 'DTR-Mart integra IA en toda la cadena de suministro, personaliza la experiencia de compra y optimiza las operaciones para socios globales.'
  },
  'mission.title': {
    vi: 'Sứ mệnh & <span>Tầm nhìn</span>',
    'en-US': 'Mission & <span>Vision</span>',
    'en-GB': 'Mission & <span>Vision</span>',
    zh: '使命与<span>愿景</span>',
    ko: '사명과 <span>비전</span>',
    ja: 'ミッションと<span>ビジョン</span>',
    fr: 'Mission & <span>Vision</span>',
    de: 'Mission & <span>Vision</span>',
    es: 'Misión y <span>Visión</span>'
  },
  'mission.subtitle': { vi: 'Giá trị chúng tôi theo đuổi', 'en-US': 'The values we pursue', 'en-GB': 'The values we pursue', zh: '我们追求的价值', ko: '우리가 추구하는 가치', ja: '私たちが追求する価値', fr: 'Les valeurs que nous poursuivons', de: 'Die Werte, die wir verfolgen', es: 'Los valores que perseguimos' },
  'mission.mission.title': { vi: 'Sứ mệnh', 'en-US': 'Mission', 'en-GB': 'Mission', zh: '使命', ko: '사명', ja: 'ミッション', fr: 'Mission', de: 'Mission', es: 'Misión' },
  'mission.mission.desc': {
    vi: 'Kết nối người mua và nhà cung cấp toàn cầu bằng nền tảng thương mại số minh bạch, nhanh chóng và đáng tin cậy — giúp mọi doanh nghiệp, dù nhỏ nhất, đều có thể vươn ra thế giới.',
    'en-US': 'Connecting buyers and suppliers globally through a transparent, fast and reliable digital commerce platform — empowering every business, however small, to reach the world.',
    'en-GB': 'Connecting buyers and suppliers globally through a transparent, fast and reliable digital commerce platform — empowering every business, however small, to reach the world.',
    zh: '通过透明、快速、可靠的数字商务平台连接全球买家和供应商——让每一家企业，无论多小，都能走向世界。',
    ko: '투명하고 빠르며 신뢰할 수 있는 디지털 커머스 플랫폼으로 전 세계 구매자와 공급업체를 연결합니다 — 아무리 작은 기업이라도 세계로 나아갈 수 있도록 돕습니다.',
    ja: '透明で迅速かつ信頼できるデジタルコマースプラットフォームで世界中の買い手と売り手をつなぎます — どんなに小さな企業でも世界に羽ばたけるように。',
    fr: "Connecter acheteurs et fournisseurs dans le monde entier grâce à une plateforme de commerce numérique transparente, rapide et fiable — permettant à chaque entreprise, même la plus petite, d'atteindre le monde.",
    de: 'Wir verbinden Käufer und Lieferanten weltweit über eine transparente, schnelle und zuverlässige digitale Handelsplattform — damit jedes Unternehmen, egal wie klein, die Welt erreichen kann.',
    es: 'Conectamos compradores y proveedores a nivel mundial a través de una plataforma de comercio digital transparente, rápida y confiable — permitiendo a cada empresa, por pequeña que sea, llegar al mundo.'
  },
  'mission.vision.title': { vi: 'Tầm nhìn', 'en-US': 'Vision', 'en-GB': 'Vision', zh: '愿景', ko: '비전', ja: 'ビジョン', fr: 'Vision', de: 'Vision', es: 'Visión' },
  'mission.vision.desc': {
    vi: 'Trở thành nền tảng thương mại số hàng đầu Đông Nam Á vào năm 2030, với hệ sinh thái kết nối hơn 100 quốc gia và 1 triệu đối tác kinh doanh trên toàn cầu.',
    'en-US': 'To become the leading digital commerce platform in Southeast Asia by 2030, with an ecosystem connecting over 100 countries and 1 million business partners worldwide.',
    'en-GB': 'To become the leading digital commerce platform in Southeast Asia by 2030, with an ecosystem connecting over 100 countries and 1 million business partners worldwide.',
    zh: '到2030年成为东南亚领先的数字商务平台，生态系统连接全球100多个国家和100万商业伙伴。',
    ko: '2030년까지 동남아시아 최고의 디지털 커머스 플랫폼이 되어 100개 이상 국가와 100만 비즈니스 파트너를 연결하는 생태계를 구축합니다.',
    ja: '2030年までに東南アジアを代表するデジタルコマースプラットフォームとなり、100カ国以上と100万のビジネスパートナーをつなぐエコシステムを構築します。',
    fr: "Devenir la première plateforme de commerce numérique d'Asie du Sud-Est d'ici 2030, avec un écosystème reliant plus de 100 pays et 1 million de partenaires commerciaux dans le monde.",
    de: 'Bis 2030 die führende digitale Handelsplattform in Südostasien zu werden, mit einem Ökosystem, das über 100 Länder und 1 Million Geschäftspartner weltweit verbindet.',
    es: 'Convertirnos en la plataforma líder de comercio digital del sudeste asiático para 2030, con un ecosistema que conecte más de 100 países y 1 millón de socios comerciales en todo el mundo.'
  },
  'mission.values.title': { vi: 'Giá trị cốt lõi', 'en-US': 'Core Values', 'en-GB': 'Core Values', zh: '核心价值观', ko: '핵심 가치', ja: 'コアバリュー', fr: 'Valeurs fondamentales', de: 'Kernwerte', es: 'Valores fundamentales' },
  'mission.values.desc': {
    vi: 'Minh bạch — Đổi mới — Khách hàng là trung tâm — Bền vững — Tôn trọng đối tác. Chúng tôi xây dựng niềm tin qua từng giao dịch và không ngừng đổi mới để phục vụ tốt hơn.',
    'en-US': 'Transparency — Innovation — Customer-centric — Sustainability — Respect for partners. We build trust through every transaction and constantly innovate to serve better.',
    'en-GB': 'Transparency — Innovation — Customer-centric — Sustainability — Respect for partners. We build trust through every transaction and constantly innovate to serve better.',
    zh: '透明 — 创新 — 以客户为中心 — 可持续 — 尊重合作伙伴。我们通过每一笔交易建立信任，不断创新以更好地服务。',
    ko: '투명성 — 혁신 — 고객 중심 — 지속 가능성 — 파트너 존중. 우리는 모든 거래를 통해 신뢰를 쌓고 더 나은 서비스를 위해 끊임없이 혁신합니다.',
    ja: '透明性 — イノベーション — 顧客中心 — 持続可能性 — パートナーへの敬意。あらゆる取引で信頼を築き、より良いサービスに向けて絶えず革新します。',
    fr: "Transparence — Innovation — Centré client — Durabilité — Respect des partenaires. Nous bâtissons la confiance à travers chaque transaction et innovons constamment pour mieux servir.",
    de: 'Transparenz — Innovation — Kundenorientierung — Nachhaltigkeit — Respekt für Partner. Wir schaffen Vertrauen durch jede Transaktion und innovieren ständig, um besser zu dienen.',
    es: 'Transparencia — Innovación — Centrado en el cliente — Sostenibilidad — Respeto por los socios. Construimos confianza en cada transacción e innovamos constantemente para servir mejor.'
  },
  'mission.commitment.title': { vi: 'Cam kết', 'en-US': 'Commitment', 'en-GB': 'Commitment', zh: '承诺', ko: '약속', ja: 'コミットメント', fr: 'Engagement', de: 'Verpflichtung', es: 'Compromiso' },
  'mission.commitment.desc': {
    vi: 'Chúng tôi cam kết bảo vệ quyền lợi của khách hàng và đối tác bằng chính sách minh bạch, dịch vụ tận tâm và trách nhiệm giải trình trong mọi giao dịch.',
    'en-US': 'We are committed to protecting the rights of customers and partners through transparent policies, attentive service and accountability in every transaction.',
    'en-GB': 'We are committed to protecting the rights of customers and partners through transparent policies, attentive service and accountability in every transaction.',
    zh: '我们承诺通过透明的政策、贴心的服务和每笔交易的问责制，保护客户和合作伙伴的权益。',
    ko: '우리는 투명한 정책, 세심한 서비스, 모든 거래에 대한 책임을 통해 고객과 파트너의 권리를 보호할 것을 약속합니다.',
    ja: '透明なポリシー、細やかなサービス、すべての取引における説明責任を通じて、お客様とパートナーの権利を守ることをお約束します。',
    fr: "Nous nous engageons à protéger les droits des clients et des partenaires grâce à des politiques transparentes, un service attentif et une responsabilité à chaque transaction.",
    de: 'Wir verpflichten uns, die Rechte von Kunden und Partnern durch transparente Richtlinien, aufmerksamen Service und Verantwortlichkeit bei jeder Transaktion zu schützen.',
    es: 'Nos comprometemos a proteger los derechos de clientes y socios mediante políticas transparentes, servicio atento y responsabilidad en cada transacción.'
  },
  'cs.title': {
    vi: 'Dịch vụ <span>khách hàng</span>',
    'en-US': 'Customer <span>Service</span>',
    'en-GB': 'Customer <span>Service</span>',
    zh: '<span>客户</span>服务',
    ko: '<span>고객</span> 서비스',
    ja: '<span>カスタマー</span>サービス',
    fr: 'Service <span>client</span>',
    de: '<span>Kunden</span>service',
    es: 'Servicio al <span>cliente</span>'
  },
  'cs.subtitle': { vi: 'Hỗ trợ bạn mọi lúc, mọi nơi', 'en-US': 'Supporting you anytime, anywhere', 'en-GB': 'Supporting you anytime, anywhere', zh: '随时随地为您提供支持', ko: '언제 어디서나 지원합니다', ja: 'いつでもどこでもサポート', fr: 'Nous vous accompagnons partout, à tout moment', de: 'Wir unterstützen Sie jederzeit und überall', es: 'Te apoyamos en cualquier momento y lugar' },
  'cs.help.title': { vi: 'Trung tâm hỗ trợ', 'en-US': 'Help Center', 'en-GB': 'Help Centre', zh: '帮助中心', ko: '지원 센터', ja: 'ヘルプセンター', fr: "Centre d'aide", de: 'Hilfe-Center', es: 'Centro de ayuda' },
  'cs.help.desc': { vi: 'Tài liệu hướng dẫn, video tutorial và cẩm nang sử dụng dịch vụ.', 'en-US': 'Guides, video tutorials and manuals for using our services.', 'en-GB': 'Guides, video tutorials and manuals for using our services.', zh: '使用我们服务的指南、视频教程和手册。', ko: '서비스 이용을 위한 가이드, 비디오 튜토리얼 및 매뉴얼.', ja: 'サービスのご利用ガイド、ビデオチュートリアル、マニュアル。', fr: "Guides, tutoriels vidéo et manuels d'utilisation de nos services.", de: 'Anleitungen, Video-Tutorials und Handbücher zur Nutzung unserer Dienste.', es: 'Guías, tutoriales en video y manuales para usar nuestros servicios.' },
  'cs.faq.title': { vi: 'Câu hỏi thường gặp', 'en-US': 'FAQ', 'en-GB': 'FAQ', zh: '常见问题', ko: '자주 묻는 질문', ja: 'よくある質問', fr: 'FAQ', de: 'FAQ', es: 'Preguntas frecuentes' },
  'cs.faq.desc': { vi: 'Giải đáp nhanh các thắc mắc phổ biến về thanh toán, đơn hàng, bảo hành.', 'en-US': 'Quick answers to common questions about payments, orders and warranty.', 'en-GB': 'Quick answers to common questions about payments, orders and warranty.', zh: '关于付款、订单和保修的常见问题快速解答。', ko: '결제, 주문 및 보증에 관한 일반적인 질문에 대한 빠른 답변.', ja: 'お支払い、ご注文、保証に関するよくある質問への迅速な回答。', fr: 'Réponses rapides aux questions courantes sur les paiements, commandes et garanties.', de: 'Schnelle Antworten auf häufige Fragen zu Zahlungen, Bestellungen und Garantie.', es: 'Respuestas rápidas a preguntas comunes sobre pagos, pedidos y garantía.' },
  'cs.contact.title': { vi: 'Liên hệ hỗ trợ', 'en-US': 'Contact Support', 'en-GB': 'Contact Support', zh: '联系支持', ko: '지원 문의', ja: 'サポートに連絡', fr: 'Contacter le support', de: 'Support kontaktieren', es: 'Contactar soporte' },
  'cs.contact.desc': { vi: 'Gọi hotline 1900 xxxx hoặc gửi email — đội ngũ phản hồi trong 30 phút.', 'en-US': 'Call hotline 1900 xxxx or send an email — our team replies within 30 minutes.', 'en-GB': 'Call hotline 1900 xxxx or send an email — our team replies within 30 minutes.', zh: '致电热线 1900 xxxx 或发送邮件 — 我们团队30分钟内回复。', ko: '핫라인 1900 xxxx로 전화하거나 이메일을 보내주세요 — 30분 이내에 답변드립니다.', ja: 'ホットライン 1900 xxxx にお電話いただくか、メールをお送りください — 30分以内に返信いたします。', fr: 'Appelez le 1900 xxxx ou envoyez un email — notre équipe répond en 30 minutes.', de: 'Rufen Sie die Hotline 1900 xxxx an oder senden Sie eine E-Mail — unser Team antwortet innerhalb von 30 Minuten.', es: 'Llama a la línea 1900 xxxx o envía un correo — nuestro equipo responde en 30 minutos.' },
  'cs.chat.title': { vi: 'Live Chat 24/7', 'en-US': 'Live Chat 24/7', 'en-GB': 'Live Chat 24/7', zh: '24/7 在线客服', ko: '24/7 라이브 채팅', ja: '24/7 ライブチャット', fr: 'Chat en direct 24/7', de: 'Live-Chat 24/7', es: 'Chat en vivo 24/7' },
  'cs.chat.desc': { vi: 'Trò chuyện trực tuyến với nhân viên hỗ trợ bất cứ lúc nào bạn cần.', 'en-US': 'Chat online with our support team whenever you need.', 'en-GB': 'Chat online with our support team whenever you need.', zh: '随时与我们的支持团队在线聊天。', ko: '필요할 때 언제든 지원팀과 온라인으로 채팅하세요.', ja: '必要なときにいつでもサポートチームとオンラインチャット。', fr: "Discutez en ligne avec notre équipe d'assistance quand vous en avez besoin.", de: 'Chatten Sie online mit unserem Support-Team, wann immer Sie möchten.', es: 'Chatea en línea con nuestro equipo de soporte cuando lo necesites.' },
  'cs.track.title': { vi: 'Tra cứu đơn hàng', 'en-US': 'Order Tracking', 'en-GB': 'Order Tracking', zh: '订单追踪', ko: '주문 추적', ja: '注文追跡', fr: 'Suivi de commande', de: 'Sendungsverfolgung', es: 'Seguimiento de pedidos' },
  'cs.track.desc': { vi: 'Theo dõi trạng thái đơn hàng theo mã vận đơn hoặc mã đơn hàng.', 'en-US': 'Track your order status using the tracking or order number.', 'en-GB': 'Track your order status using the tracking or order number.', zh: '使用运单号或订单号追踪订单状态。', ko: '운송장 번호 또는 주문 번호로 주문 상태를 추적하세요.', ja: '追跡番号または注文番号で注文状況を確認できます。', fr: 'Suivez le statut de votre commande avec le numéro de suivi ou de commande.', de: 'Verfolgen Sie den Status Ihrer Bestellung mit der Sendungs- oder Bestellnummer.', es: 'Rastrea el estado de tu pedido con el número de seguimiento o pedido.' },
  'cs.warranty.title': { vi: 'Bảo hành & đổi trả', 'en-US': 'Warranty & Returns', 'en-GB': 'Warranty & Returns', zh: '保修与退货', ko: '보증 및 반품', ja: '保証と返品', fr: 'Garantie & retours', de: 'Garantie & Rückgabe', es: 'Garantía y devoluciones' },
  'cs.warranty.desc': { vi: 'Chính sách bảo hành 1 đổi 1 trong 30 ngày cho sản phẩm lỗi.', 'en-US': '1-for-1 warranty within 30 days for defective products.', 'en-GB': '1-for-1 warranty within 30 days for defective products.', zh: '缺陷产品30天内一对一换货保修。', ko: '결함 제품에 대해 30일 이내 1:1 교환 보증.', ja: '不良品は30日以内の1対1交換保証。', fr: 'Garantie 1 pour 1 sous 30 jours pour les produits défectueux.', de: '1-zu-1-Garantie innerhalb von 30 Tagen für defekte Produkte.', es: 'Garantía 1 a 1 dentro de 30 días para productos defectuosos.' },
  'footer.brand.desc': {
    vi: 'Nền tảng thương mại số kết nối 50+ quốc gia với hơn 38.000 sản phẩm kỹ thuật số. Digital Tech Resolution — thương mại không biên giới.',
    'en-US': 'A digital commerce platform connecting 50+ countries with over 38,000 digital products. Digital Tech Resolution — commerce without borders.',
    'en-GB': 'A digital commerce platform connecting 50+ countries with over 38,000 digital products. Digital Tech Resolution — commerce without borders.',
    zh: '连接 50 多个国家与 38,000 多种数字产品的数字商务平台。Digital Tech Resolution — 无国界贸易。',
    ko: '50개 이상의 국가와 38,000개 이상의 디지털 제품을 연결하는 디지털 커머스 플랫폼. Digital Tech Resolution — 국경 없는 상거래.',
    ja: '50カ国以上と38,000以上のデジタル製品をつなぐデジタルコマースプラットフォーム。Digital Tech Resolution — 国境のない商取引。',
    fr: 'Une plateforme de commerce numérique reliant plus de 50 pays avec plus de 38 000 produits numériques. Digital Tech Resolution — le commerce sans frontières.',
    de: 'Eine digitale Handelsplattform, die über 50 Länder mit mehr als 38.000 digitalen Produkten verbindet. Digital Tech Resolution — Handel ohne Grenzen.',
    es: 'Una plataforma de comercio digital que conecta más de 50 países con más de 38.000 productos digitales. Digital Tech Resolution — comercio sin fronteras.'
  },
  'footer.products.title': { vi: 'Sản phẩm', 'en-US': 'Products', 'en-GB': 'Products', zh: '产品', ko: '제품', ja: '製品', fr: 'Produits', de: 'Produkte', es: 'Productos' },
  'footer.products.games': { vi: 'Trò chơi', 'en-US': 'Games', 'en-GB': 'Games', zh: '游戏', ko: '게임', ja: 'ゲーム', fr: 'Jeux', de: 'Spiele', es: 'Juegos' },
  'footer.products.movies': { vi: 'Phim ảnh', 'en-US': 'Movies', 'en-GB': 'Movies', zh: '电影', ko: '영화', ja: '映画', fr: 'Films', de: 'Filme', es: 'Películas' },
  'footer.products.digital': { vi: 'Sản phẩm kỹ thuật số', 'en-US': 'Digital products', 'en-GB': 'Digital products', zh: '数字产品', ko: '디지털 제품', ja: 'デジタル製品', fr: 'Produits numériques', de: 'Digitale Produkte', es: 'Productos digitales' },
  'footer.products.electronics': { vi: 'Điện tử & công nghiệp', 'en-US': 'Electronics & Industrial', 'en-GB': 'Electronics & Industrial', zh: '电子与工业', ko: '전자 및 산업', ja: '電子・産業', fr: 'Électronique & Industriel', de: 'Elektronik & Industrie', es: 'Electrónica e Industrial' },
  'footer.company.title': { vi: 'Công ty', 'en-US': 'Company', 'en-GB': 'Company', zh: '公司', ko: '회사', ja: '会社', fr: 'Entreprise', de: 'Unternehmen', es: 'Empresa' },
  'footer.company.about': { vi: 'Về DTR-Mart', 'en-US': 'About DTR-Mart', 'en-GB': 'About DTR-Mart', zh: '关于 DTR-Mart', ko: 'DTR-Mart 소개', ja: 'DTR-Mart について', fr: 'À propos de DTR-Mart', de: 'Über DTR-Mart', es: 'Sobre DTR-Mart' },
  'footer.company.partners': { vi: 'Đối tác & nhà cung cấp', 'en-US': 'Partners & Suppliers', 'en-GB': 'Partners & Suppliers', zh: '合作伙伴与供应商', ko: '파트너 및 공급업체', ja: 'パートナーとサプライヤー', fr: 'Partenaires & Fournisseurs', de: 'Partner & Lieferanten', es: 'Socios y Proveedores' },
  'footer.company.sell': { vi: 'Đăng ký bán hàng', 'en-US': 'Become a Seller', 'en-GB': 'Become a Seller', zh: '注册成为卖家', ko: '판매자 등록', ja: '販売者登録', fr: 'Devenir vendeur', de: 'Verkäufer werden', es: 'Convertirse en vendedor' },
  'footer.company.careers': { vi: 'Tuyển dụng', 'en-US': 'Careers', 'en-GB': 'Careers', zh: '招聘', ko: '채용', ja: '採用情報', fr: 'Carrières', de: 'Karriere', es: 'Empleo' },
  'footer.support.title': { vi: 'Hỗ trợ', 'en-US': 'Support', 'en-GB': 'Support', zh: '支持', ko: '지원', ja: 'サポート', fr: 'Support', de: 'Support', es: 'Soporte' },
  'footer.support.privacy': { vi: 'Chính sách bảo mật', 'en-US': 'Privacy Policy', 'en-GB': 'Privacy Policy', zh: '隐私政策', ko: '개인정보 처리방침', ja: 'プライバシーポリシー', fr: 'Politique de confidentialité', de: 'Datenschutzrichtlinie', es: 'Política de privacidad' },
  'footer.subscribe.title': { vi: 'Nhận tin mới', 'en-US': 'Newsletter', 'en-GB': 'Newsletter', zh: '订阅新闻', ko: '뉴스레터', ja: 'ニュースレター', fr: 'Newsletter', de: 'Newsletter', es: 'Boletín' },
  'footer.subscribe.desc': {
    vi: 'Cập nhật ưu đãi, sản phẩm mới và tin tức công nghệ từ DTR-Mart.',
    'en-US': 'Get updates on deals, new products and tech news from DTR-Mart.',
    'en-GB': 'Get updates on deals, new products and tech news from DTR-Mart.',
    zh: '获取 DTR-Mart 的优惠、新产品和科技新闻。',
    ko: 'DTR-Mart의 특가, 신제품 및 기술 뉴스를 받아보세요.',
    ja: 'DTR-Mart のお得情報、新製品、テックニュースをお届けします。',
    fr: 'Recevez les offres, nouveautés et actualités tech de DTR-Mart.',
    de: 'Erhalten Sie Angebote, neue Produkte und Tech-News von DTR-Mart.',
    es: 'Recibe ofertas, nuevos productos y noticias tech de DTR-Mart.'
  },
  'footer.subscribe.placeholder': { vi: 'Email của bạn', 'en-US': 'Your email', 'en-GB': 'Your email', zh: '您的邮箱', ko: '이메일', ja: 'メールアドレス', fr: 'Votre email', de: 'Ihre E-Mail', es: 'Tu correo' },
  'footer.subscribe.button': { vi: 'Đăng ký', 'en-US': 'Subscribe', 'en-GB': 'Subscribe', zh: '订阅', ko: '구독', ja: '購読', fr: "S'abonner", de: 'Abonnieren', es: 'Suscribirse' },
  'footer.privacy': { vi: 'Chính sách bảo mật', 'en-US': 'Privacy Policy', 'en-GB': 'Privacy Policy', zh: '隐私政策', ko: '개인정보 처리방침', ja: 'プライバシーポリシー', fr: 'Politique de confidentialité', de: 'Datenschutzrichtlinie', es: 'Política de privacidad' },
  'footer.terms': { vi: 'Điều khoản sử dụng', 'en-US': 'Terms of Use', 'en-GB': 'Terms of Use', zh: '使用条款', ko: '이용약관', ja: '利用規約', fr: "Conditions d'utilisation", de: 'Nutzungsbedingungen', es: 'Términos de uso' },
  'footer.status': { vi: 'Trạng thái hệ thống', 'en-US': 'System Status', 'en-GB': 'System Status', zh: '系统状态', ko: '시스템 상태', ja: 'システムステータス', fr: 'État du système', de: 'Systemstatus', es: 'Estado del sistema' },
  'footer.cookie': { vi: 'Cookie', 'en-US': 'Cookies', 'en-GB': 'Cookies', zh: 'Cookie', ko: '쿠키', ja: 'Cookie', fr: 'Cookies', de: 'Cookies', es: 'Cookies' },
  'footer.sitemap': { vi: 'Sitemap', 'en-US': 'Sitemap', 'en-GB': 'Sitemap', zh: '网站地图', ko: '사이트맵', ja: 'サイトマップ', fr: 'Plan du site', de: 'Sitemap', es: 'Mapa del sitio' }
};